create schema gestion;
CREATE TABLE gestion.users (
username VARCHAR(50) NOT NULL PRIMARY KEY,
password VARCHAR(50) NOT NULL,
enabled numeric
);
CREATE TABLE gestion.authorities (
username VARCHAR(50) NOT NULL,
authority VARCHAR(50) NOT NULL
);
INSERT INTO gestion.USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin', 'admin', 1);
INSERT INTO gestion.USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user', 'user', 1);
INSERT INTO GESTION.AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user', 'ROLE_USER') ;
INSERT INTO GESTION.AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN') ;
INSERT INTO GESTION.AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_USER') ;